# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
ENV['SWIFT_VERSION'] = '5'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'


# 添加模块儿所在路径

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'DartNativeDemo' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MJExtension'
  # Pods for DartNativeDemo
  install_all_flutter_pods(flutter_application_path)

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    
  end
end
